project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /locales/en-GB.json
    translation: /locales/%locale%.json
    dest: /site/%file_name%.json
    type: json
